Correct function names and bash variable substitutions

diff --git a/functions/module-utils b/functions/module-utils
--- a/functions/module-utils
+++ b/functions/module-utils
@@ -1,5 +1,5 @@
 # Finds which compiler module is loaded
-get-compiler_module() {
+get_compiler_module() {
   export COMPILER_MODULE
   local ccmod
   for ccmod in $(find /shared/ucl/apps/modulefiles/compilers -type f | cut -d'/' -f7-)
@@ -16,25 +16,26 @@ get-compiler_module() {
 # Constructs the modulefile name by taking the compiler module (e.g.
 # compilers/intel/2015/update2), stripping off the leading 'compilers/' and
 # and replacing the remaining '/'s with '-' (e.g. intel-2015-update2).
-get-module_string() {
-  get-compiler_module || die "Unable to find compiler module"
+get_module_string() {
+  get_compiler_module || die "Unable to find compiler module"
   export MODULE_STRING=${COMPILER_MODULE#*/*}
-  MODULE_STRING=${MODULE_STRING/\//-/}
+  MODULE_STRING=${MODULE_STRING//\//-}
 }
 
 # Constructs the modulefile path as
 # ${PREFIX}/modulefiles/${PN}/${PV}/${MODULE_STRING}
-get-module_file() {
-  get-module_string || die "Unable to construct module string"
+get_module_file() {
+  get_module_string || die "Unable to construct module string"
   export MODULE_FILE="${MODULE_FILE:-${PREFIX}/modulefiles/${PN}/${PV}/${MODULE_STRING}}"
 }
 
 write_module_file() {
-get-module_file || die "Unable to get module file path"
-local module_depstring="", dep
-for dep in "${MODULE_DEPENDS}"
+get_module_file || die "Unable to get module file path"
+local module_depstring=""
+for dep in ${MODULE_DEPENDS}
   do
-  module_depstring = "${module_depstring}\nprereq ${dep}"
+  module_depstring="${module_depstring}
+prereq ${dep}"
 done
 mkdir -p "${MODULE_FILE%/*}" && \
 cat > "${MODULE_FILE}" <<EOF
