Improves error handling in post_build_report and remote_run_build
Before, if you set -o pipefail -o errexit in bash, and had more than 10 executables, post_build_report would make your script exit with status (128+SIGPIPE=141), when find | head terminated. Now it specifically tests for that condition, because it isn't an error.

Also if the buildscript exits with a non-zero status, remote_run_build tells you what the status is.

diff --git a/remote_run_build b/remote_run_build
--- a/remote_run_build
+++ b/remote_run_build
@@ -26,7 +26,7 @@ cd "$BUILDSCRIPT_REPO_DIR" || exit 3
 
 
 function build_fail_stop () {
-    echo "Error: build failed. Check the build logs." >&2
+    echo "Error: build failed (status $?). Check the build logs." >&2
     exit 4
 }
 
